### ISSUE TITLE
Source Code documentation

### ISSUE THREAD

**Issue by wsojka00** [JamesBremner/PathFinder2#1]
Hey James,

thank you very much for creating this repository, it will be very useful for my work. However, I would like to ask you to provide more "goal-oriented" documentation and navigation through the code, if it's possible. Could you shortly describe what I can find in folders and which code stands for what functionalities? 

It would be very great for me, also because I've never worked on C++, only in Python. 

Thank you very much for any effort in advance! :)

**Comment by JamesBremner** [comment]
> shortly describe what I can find in folders 

All the code is in one folder `./src`

You can ignore the other folders ( unless you intend to build or run the application.

>which code stands for what functionalities?

All the class interfaces are both defined AND documented in the header files ( *.h ).  You have two options: a) browse the *.h files using an editor or an IDE b) Extract the documentation using doxygen and then use a web browser to browse the html.  I reccomend option b).

Let me know if there is any specific method whose documentation is missing or unclear and I will add it.

**Comment by JamesBremner** [comment]
The majority of the wiki is a user manual for the application.  However, you can find a discussion of the cGraph class design at https://github.com/JamesBremner/PathFinder/wiki/cGraph-Class-Design.

I  think the other class designs are obvious.  Let me know if that is not the case.

**Comment by JamesBremner** [comment]
Perhaps you are not familiar with Doxygen?

The attached zip contains the doxygen output.

- Download and unzip
- Click and drag the file `html/index.html` into a web browser tab
- Browse

[doxygen.zip](https://github.com/JamesBremner/PathFinder/files/7755909/doxygen.zip)

**Comment by JamesBremner** [comment]
Hello?  I have not heard from you in 24 hours!

Do you have any specific places in the code that you would like me to add to documentation?

Or should I close this issue?

**Comment by wsojka00** [comment]
Hello James, 

Could you give me another 24 hours? I have some stuff to do, and I was planning to sit and go through what you wrote tomorrow. I'll let you know if I'll have any other issues.

Thank you for your effort!

**Comment by JamesBremner** [comment]
OK
